/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_iperf3ericsson_MainActivity.h"

/* Header for class com_iperf3ericsson_MainActivity */

JNIEXPORT jstring JNICALL Java_com_iperf3ericsson_MainActivity_callNative
  (JNIEnv *env, jobject obj){

    return (*env) ->NewStringUTF(env, "nimabi");

  }

